name: ha2
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
